### ISSUE TITLE
sire.run download link does not work

### ISSUE THREAD

**Issue by ppxasjsm** [chryswoods/siremol.org#2] opened 2017-01-03 15:42 UTC
The link to download the latest release does not work:
http://siremol.org/pages/binaries.html

**Comment by chryswoods** [comment] 2017-01-04 10:21
Thanks for letting me know. I updated the download.php yesterday. and while initial tests were fine, it seems to have problems with some IP addresses. I will investigate now...

**Comment by chryswoods** [comment] 2017-01-04 17:46
Ahh - my initial tests were fine as the bug was only triggered by downloading from a new IP address (I cache so much..!). It was caused by a missing function which I have patched. As an aside, it also forced me to fix the issue with my website provider disabling file_get_contents in php, which broke GeoIP lookup in the phonehome code, and also the new download.php code. I have fixed this, so the country data in the analytics is now more accurate.

Could you confirm that you can download now. I've tested with a new IP address, so am more confident. If it works, please feel free to close this issue.

**Comment by ppxasjsm** [comment] 2017-01-05 09:44
Wow, that sounded more complicated to fix this. It works now! Thanks.

**Closed as completed** 2017-01-05 11:12 UTC
